INSERT INTO Types (Type, Kind)
VALUES ('ABILITY_UAH_LYSEFJORD_PROMOTION', 'KIND_ABILITY');

INSERT INTO UnitAbilities (UnitAbilityType, Name, Description)
VALUES ('ABILITY_UAH_LYSEFJORD_PROMOTION', 'LOC_HUD_UNIT_CHOOSE_PROMOTION_TEXT', 'LOC_GREATPERSON_ARTEMISIA_ACTIVE');